FROM --platform=$BUILDPLATFORM rust:alpine3.15 AS rustbuilder

WORKDIR /app

ENV GRPC_HOST=0.0.0.0:50053

RUN apk upgrade --update-cache --available && \
	apk add npm gcc cmake make g++

RUN npm install @a11ywatch/protos

COPY . .

RUN cargo install --no-default-features --path .

FROM node:18.8.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .
COPY --from=rustbuilder /usr/local/cargo/bin/health_client /usr/local/bin/health_client

CMD ["node_modules/ts-node-dev/lib/bin.js", "--no-experimental-fetch", "--transpile-only", "-r", "tsconfig-paths/register", "src/server.ts"]