FROM --platform=$BUILDPLATFORM rustlang/rust:nightly AS rustbuilder

WORKDIR /app

ENV GRPC_HOST=0.0.0.0:50053

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gcc cmake libc6 npm

RUN npm install @a11ywatch/protos

COPY . .

RUN cargo install --no-default-features --path .

FROM node:18.7-buster-slim

WORKDIR /usr/src/app

# todo MULTI STAGE BUILD
RUN apt-get update && \ 
	apt-get install -y build-essential \
	wget \
	bash \
	python3 \
    pkg-config \
	make \
	gcc

COPY package*.json ./

RUN npm ci

COPY . .
COPY --from=rustbuilder /usr/local/cargo/bin/health_client /usr/local/bin/health_client

CMD ["node_modules/ts-node-dev/lib/bin.js", "--no-experimental-fetch", "--transpile-only", "-r", "tsconfig-paths/register", "src/server.ts"]